# Numpy Examples

## 1) Computation with arrays

### a) Sigmoid activation function of a vector

In [3]:
import numpy as np
x = np.array([4, -1, 7, 9, 3, -5])

**Apply the Sigmoid activation function: $y = sigmoid(x)$**
$$sigmoid(x_i) = \frac{1}{1+exp(-x_i)}$$
<img src='./sigmoid.png' width='40%'>

In [18]:
def sigmoid(val:np.array) -> np.array:
    """
        Compute the sigmoid of the given array
    Args:
        val (np.array): input array

    Returns:
        np.array: output array
    """
    return (1+np.exp(-val))**(-1)

In [16]:
sigmoid(x)

array([0.98201379, 0.26894142, 0.99908895, 0.99987661, 0.95257413,
       0.00669285])

### b) Softmax activation function

Activation function that normalizes the input vector (z) to a discrete probability distribution (values of the result add to 1).

$$y_i = \frac{exp(x_i)}{\sum_j{exp(x_j)}}$$

In [23]:
def softmax(ary: np.array) -> np.array:
    """
        Return the array where softmax function was applied element
        by element

    Args:
        ary (np.array): input array

    Returns:
        np.array: output array
    """
    ary_to_return = []
    denominator = np.sum(np.exp(ary))
    
    for element in ary:
        numerator = np.exp(element)
        ary_to_return.append(numerator/denominator)
    
    return np.array(ary_to_return)

In [24]:
softmax(x)

array([5.88673555e-03, 3.96645122e-05, 1.18238244e-01, 8.73669020e-01,
       2.16560899e-03, 7.26480881e-07])

## 2) Broadcasting: dataset normalization

In [25]:
# Input table
n_samples = 100
n_columns = 5
mean = 1
std = 3
X = np.random.normal(mean, std, (n_samples, n_columns))

In [28]:
X.shape

(100, 5)

** Apply z-score: normalize each column by subtracting its mean and dividing by its standard deviation **

In [33]:
def z_score_norm(ary:np.ndarray) -> np.ndarray:
    """
        Return the normalized array. It is normalized by subtracting
        mean of each column to each column and divided by the std of 
        each column

    Args:
        ary (np.ndarray): input array

    Returns:
        np.ndarray: output array
    """
    mean = compute_column_mean(ary)
    std = compute_column_std(ary)
    return (ary - mean)/std

def compute_column_mean(ary:np.ndarray) -> np.ndarray:
    """
       Return the mean of each column

    Args:
        ary (np.ndarray): input array

    Returns:
        np.ndarray: output array
    """
    if len(ary.shape) == 2:
        return np.mean(ary, axis=0)
    elif len(ary.shape) == 3:
        return np.mean(ary, axis=1)
    else:
        return np.mean(ary, axis=-1)

def compute_column_std(ary:np.ndarray) -> np.ndarray:
    """
       Return the std of each column

    Args:
        ary (np.ndarray): input array

    Returns:
        np.ndarray: output array
    """
    if len(ary.shape) == 2:
        return np.std(ary, axis=0)
    elif len(ary.shape) == 3:
        return np.std(ary, axis=1)
    else:
        return np.std(ary, axis=-1)

In [32]:
z_score_norm(X)

array([2.86971434, 2.94702976, 3.24789191, 3.3751469 , 2.96040358])

## 3) Accessing Numpy Arrays

In [ ]:
#Input data
import numpy as np

# Input table (12 samples x 4 attributes)
X = np.array([[5.1, 3.5, 1.4, 0.2],
           [4.3, 3. , 1.1, 0.1],
           [5. , 3.4, 1.6, 0.4],
           [5.1, 3.4, 1.5, 0.2],
           [6.9, 3.1, 4.9, 1.5],
           [6.7, 3.1, 4.4, 1.4],
           [6. , 2.9, 4.5, 1.5],
           [6.1, 3. , 4.6, 1.4],
           [6.5, 3. , 5.8, 2.2],
           [7.7, 3.8, 6.7, 2.2],
           [7.4, 2.8, 6.1, 1.9],
           [6.8, 3.2, 5.9, 2.3]])
# Column names
columns = ['height','width','intensity','weight']

# Class label of each sample
labels = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2])

In [ ]:
# Get column indices
height_i = columns.index('height')
intensity_i = columns.index('intensity')

**Compute the average height:**

**Compute the average height of samples with intensity greater than 5:**

**Compute the probability of class 2 if intensity>5**
$$p = \frac{\#(intensity>5 \land class2)}{\#(intensity>5)}$$

**Print the height of the top 3 records with highest intensity:**