# Numpy Examples

## 1) Computation with arrays 

### a) Sigmoid activation function of a vector

In [1]:
import numpy as np
x = np.array([4, -1, 7, 9, 3, -5])

**Apply the Sigmoid activation function: $y = sigmoid(x)$**
$$sigmoid(x_i) = \frac{1}{1+exp(-x_i)}$$
<img src='./sigmoid.png' width='40%'>

In [3]:
y_sigm = 1/ (1 + np.exp(-x))
y_sigm

array([0.98201379, 0.26894142, 0.99908895, 0.99987661, 0.95257413,
       0.00669285])

### b) Softmax activation function

Activation function that normalizes the input vector (z) to a discrete probability distribution (values of the result add to 1).

$$y_i = \frac{exp(x_i)}{\sum_j{exp(x_j)}}$$

In [4]:
y_soft = np.exp(x) / np.exp(x).sum()
y_soft

array([5.88673555e-03, 3.96645122e-05, 1.18238244e-01, 8.73669020e-01,
       2.16560899e-03, 7.26480881e-07])

## 2) Broadcasting: dataset normalization

In [9]:
# Input table
n_samples = 100
n_columns = 5
mean = 1
std = 3
np.random.seed(0)
X = np.random.normal(mean, std, (n_samples, n_columns))

** Apply z-score: normalize each column by subtracting its mean and dividing by its standard deviation **

In [11]:
X_norm = (X-X.mean(axis=0)) / X.std(axis=0)
X_norm

array([[ 1.85121484e+00,  4.35937637e-01,  1.03609275e+00,
         2.25758183e+00,  1.77957297e+00],
       [-8.66924873e-01,  1.01080095e+00, -9.28497305e-02,
        -8.64767513e-03,  2.73738572e-01],
       [ 2.44910663e-01,  1.53784417e+00,  8.18614550e-01,
         2.08774150e-01,  3.08119196e-01],
       [ 4.32937222e-01,  1.57945439e+00, -1.46595908e-01,
         3.93807860e-01, -1.03338088e+00],
       [-2.42930694e+00,  7.00890145e-01,  9.21907556e-01,
        -6.26365014e-01,  2.19526163e+00],
       [-1.33997670e+00,  6.54716527e-02, -1.28639829e-01,
         1.57299476e+00,  1.36801583e+00],
       [ 2.55722275e-01,  4.12945780e-01, -8.28527104e-01,
        -1.82384324e+00, -5.10216947e-01],
       [ 2.57111962e-01,  1.30370668e+00,  1.25950650e+00,
        -2.83316223e-01, -4.63077543e-01],
       [-9.37597001e-01, -1.46675838e+00, -1.64617668e+00,
         1.97710312e+00, -6.77382683e-01],
       [-3.32282734e-01, -1.29195447e+00,  8.35050399e-01,
        -1.46913473e+00

## 3) Accessing Numpy Arrays

In [12]:
#Input data
import numpy as np

# Input table (12 samples x 4 attributes)
X = np.array([[5.1, 3.5, 1.4, 0.2],
           [4.3, 3. , 1.1, 0.1],
           [5. , 3.4, 1.6, 0.4],
           [5.1, 3.4, 1.5, 0.2],
           [6.9, 3.1, 4.9, 1.5],
           [6.7, 3.1, 4.4, 1.4],
           [6. , 2.9, 4.5, 1.5],
           [6.1, 3. , 4.6, 1.4],
           [6.5, 3. , 5.8, 2.2],
           [7.7, 3.8, 6.7, 2.2],
           [7.4, 2.8, 6.1, 1.9],
           [6.8, 3.2, 5.9, 2.3]])
# Column names
columns = ['height','width','intensity','weight']

# Class label of each sample
labels = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2])

In [13]:
# Get column indices
height_i = columns.index('height')
intensity_i = columns.index('intensity')

**Compute the average height:**

In [14]:
avg_height = X[:, height_i].mean()
print("Average height: %.3f" % avg_height)

Average height: 6.133


**Compute the average height of samples with intensity greater than 5:**

In [15]:
intensity = X[:, intensity_i]
avg_height = X [intensity>5, height_i].mean()
print("Average height (intensity>5): %.3f" % avg_height)

Average height (intensity>5): 7.100


**Compute the probability of class 2 if intensity>5**
$$p = \frac{\#(intensity>5 \land class2)}{\#(intensity>5)}$$

In [16]:
intensity = X[:, intensity_i]
num = ((intensity>5) & (labels==2)).sum()
den = (intensity>5).sum()
p = num/den
print("P(class 2 | intensity>5) = %.2f" % p)

P(class 2 | intensity>5) = 0.75


**Print the height of the top 3 records with highest intensity:**

In [11]:
top3_indices = X[:, intensity_i].argsort()[-3::][::-1]
print("Top 3 elements:")
print(X[top3_indices, height_i])

Top 3 elements:
[7.7 7.4 6.8]
